openapi: 3.0.1
info:
  title: Home Assistant Light Controller Plugin
  description: A plugin that allows the user to discover and control light statuses in Home Assistant using ChatGPT.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /lights:
    get:
      operationId: discoverLights
      summary: Discover available lights in Home Assistant
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Light'
  /lights/{entity_id}:
    post:
      operationId: changeLightStatus
      summary: Change the status of a light in Home Assistant
      parameters:
        - in: path
          name: entity_id
          schema:
            type: string
          required: true
          description: The entity_id of the light to control.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LightStatusRequest'
      responses:
        "200":
          description: OK
        "400":
          description: Invalid status
        "500":
          description: Error changing light status

components:
  schemas:
    Light:
      type: object
      properties:
        entity_id:
          type: string
        state:
          type: string
    LightStatusRequest:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: [on, off]
          description: The desired status of the light, accepted values are 'on' and 'off'.
